### ISSUE TITLE
Attribute to make links open in new window

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/marked-element#4]
There should be a boolean attribute that will cause links in the parsed source to have `target="_blank"` on them.

**Comment by notwaldorf** [comment]
I'll take a look this week!

**Comment by tiffz** [comment]
I need this behavior for a project I am currently working on. Has this been looked into? I am interested in submitting a pull request to address this.

**Comment by FredKSchott** [comment]
No one has looked into this as far as I know (/cc @notwaldorf to confirm). @mbleigh @tiffz can either of you explain a bit more about this? When are urls currently turned into links (I checked out http://prismjs.com/ and didn't see this happening)?

Happy to add an additional option to send to prism, but I'm less enthusiastic about adding new plugins or writing our own parse logic on top of prism.

**Comment by tiffz** [comment]
I think this is referring to the HTML generated by marked-element, which is based on the marked library: https://github.com/chjj/marked (I'm not sure what prism has to do with this?) 

In the "Overriding renderer methods" section of their README it looks like marked already has support for adjusting the behavior of elements that are rendered. 

For the app I am working on, it breaks users' workflows to open links and have it change the page they are currently on, so it'd be really nice to have an exposed option to do this. If this doesn't seem like something in the domain of the marked-element library, then an alternative could be to expose marked's capability to override renderers in marked-element.

**Comment by FredKSchott** [comment]
haha whoops, I got my issues/repos mixed up :) Yea this sounds like a very useful thing to support.

It looks like the marked maintainers support customizing behavior by passing a custom renderer to marked (https://github.com/chjj/marked#overriding-renderer-methods) so that not every custom behavior needs a boolean option. Is there a way to use that same interface for our element? What about a function attribute that takes a renderer, customizes and overrides it, and then returns it for the element to use?

**Comment by tiffz** [comment]
I think making a function attribute that takes a renderer would be a fine approach. So, for example: 

```
<marked-element markdown="[[markdown]]" link-renderer="[[linkFunction]]">
    <div class="markdown-html"></div>
</marked-element>
```

and linkFunction could be set by the user to something like: 

```
linkFunction: function (href, title, text) {
  return `<a href="${href}" title="${title}" target="_blank">${text}</a>`;
},
```

Then marked-element could pass along the function to its own instance of a marked renderer. I think it would represent a decent amount of work to get this to work for all of the different renderer types that marked supports. For this, maybe we could just start with links.

**Comment by FredKSchott** [comment]
How about one step further, where we expose a single `renderer` attribute for all rendering customization? That way we don't need to create a mapping for every supported element.


```html
<marked-element markdown="[[markdown]]" renderer="[[customRenderer]]">
    <div class="markdown-html"></div>
</marked-element>
```

```js
customRenderer: function (renderer) {
  renderer.link = (href, title, text) => {
    return `<a href="${href}" title="${title}" target="_blank">${text}</a>`;
  };
  return renderer;
}
```

**Comment by tiffz** [comment]
I like the idea of that API. Though one caveat I realized while looking through marked is that the renderers for marked that you override contain some sanitization. For example, marked's default link renderer is: 

```
Renderer.prototype.link = function(href, title, text) {
  if (this.options.sanitize) {
    try {
      var prot = decodeURIComponent(unescape(href))
        .replace(/[^\w:]/g, '')
        .toLowerCase();
    } catch (e) {
      return '';
    }
    if (prot.indexOf('javascript:') === 0 || prot.indexOf('vbscript:') === 0 || prot.indexOf('data:') === 0) {
      return '';
    }
  }
  var out = '<a href="' + href + '"';
  if (title) {
    out += ' title="' + title + '"';
  }
  out += '>' + text + '</a>';
  return out;
};
```

This is more of a problem on marked's side I think, but this does mean their API to override renderers is very likely to encourage users to code in a way that compromises security. (ie: assuming things are okay because you set sanitized to true but not realizing that your overriding renderer undoes this).  

I don't know how significant of a problem this is, but I figured I'd put this out there. At the very least ,if we go with this route, we should note this concern in the documentation, I think.

**Comment by FredKSchott** [comment]
Added in #44
