### ISSUE TITLE
sanitize always forced to true

### ISSUE THREAD

**Issue by robrez** [PolymerElements/marked-element#69]
### Description
When binding a markdown file as the source of content, the `sanitize` flag is always set to `true`.

marked.js supports directly embedding html eg:
```
Name   | Description
-------|---------------
color  | The color. Allowable values are: <br/><ul><li>red</li><li>blue</li></ul>
```

[Line 326](https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L326) forces the sanitize property to true.

Blame shows commit [c91e398](https://github.com/PolymerElements/marked-element/commit/c91e39801e5b2b4656cd15db5209433fe06b4ae6#diff-f0b9e140535ccafe29cfe484f7fc4a11R317) as changing that line.

I'm not sure if this was intentional... mabye it existed prior to that commit . Does anyone know if there's an intent here? Can I submit a PR?

### Expected outcome

HTML inside markdown renders

### Actual outcome

HTML inside markdown is shown as text

### Live Demo

n/a

### Steps to reproduce

bind a markdown file to marked-element's source, include some html inside the md file

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by stramel** [comment]
I believe @e111077 intentionally added this. Maybe he can answer better than me.

**Comment by e111077** [comment]
Inelegant suggestion I can't believe I committed TBH. I did this because of how unsafe it is to simply have unsanitized code; especially from an XHR that can easily be changed via data binding.

I believe that `sanitize` should be `true` by default but I did not want to break the API of this element. I'll submit a PR in a bit, but what I _SHOULD_ have done was to create a property along the lines of `sanitizeSrc` or `sanitizeXHR` that defaulted to setting `sanitize` to true in the XHR.

Though this will cause some confusion between `sanitize` and this new prop, I argue that this is the correct, safer thing to do.

**Comment by robrez** [comment]
I didn't even think about the dangerous aspect of inlining html.. I'm glad it was mentioned. I'll be sure to add some sanitization in the `html(strHtml)` render method:

https://github.com/chjj/marked#overriding-renderer-methods

Thanks for the help and detailed response

**Comment by e111077** [comment]
@robrez; added the `disableRemoteSanitization` property. It still defaults to not disabling it, but at least now you can! Let me know if this helps your use case

**Comment by robrez** [comment]
Thanks again @e11077, I'm certain this will work for me
